# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    docker build -t quay.io/dgangaia/donald:latest .
    docker --version
    docker login -u="dgangaia" -p="jP3ZZ88WJekQOsjE+Hi6gsylJ4J8NVpUVRi4FMAfrQ3O/L0Dgs1Bv9Fl8o1GC/Jo" quay.io
    docker inspect quay.io/dgangaia/donald:latest
    docker push quay.io/dgangaia/donald:latest
    docker pull quay.io/dgangaia/busybox
    journalctl -u docker.service
    

